import {
  Atom,
  Bone,
  BookOpen,
  Brain,
  Bug,
  Calculator,
  Code,
  Compass,
  Cpu,
  Dna,
  Droplets,
  Earth,
  Flame,
  FlaskConical,
  HeartPulse,
  Landmark,
  Languages,
  Leaf,
  Magnet,
  Map,
  Microscope,
  Mountain,
  Music,
  Orbit,
  Palette,
  PawPrint,
  Pi,
  Rocket,
  Ruler,
  Shapes,
  Sigma,
  Sprout,
  Telescope,
  TestTube,
  Wrench,
  Zap,
  type LucideIcon,
} from "lucide-react";

export const SUBJECT_ICONS: Record<string, LucideIcon> = {
  atom: Atom,
  flask: FlaskConical,
  "test-tube": TestTube,
  dna: Dna,
  microscope: Microscope,
  leaf: Leaf,
  sprout: Sprout,
  bug: Bug,
  paw: PawPrint,
  bone: Bone,
  heart: HeartPulse,
  brain: Brain,
  earth: Earth,
  map: Map,
  mountain: Mountain,
  droplets: Droplets,
  orbit: Orbit,
  telescope: Telescope,
  rocket: Rocket,
  zap: Zap,
  magnet: Magnet,
  flame: Flame,
  calculator: Calculator,
  sigma: Sigma,
  pi: Pi,
  shapes: Shapes,
  ruler: Ruler,
  compass: Compass,
  landmark: Landmark,
  book: BookOpen,
  languages: Languages,
  music: Music,
  palette: Palette,
  cpu: Cpu,
  code: Code,
  wrench: Wrench,
};

export const SUBJECT_COLORS = [
  "#5b5bf6",
  "#8b5cf6",
  "#ec4899",
  "#ef4444",
  "#f97316",
  "#f59e0b",
  "#84cc16",
  "#10b981",
  "#14b8a6",
  "#06b6d4",
  "#0ea5e9",
  "#3b82f6",
  "#64748b",
];

export function SubjectIcon({ icon, className }: { icon: string; className?: string }) {
  const Icon = SUBJECT_ICONS[icon] ?? BookOpen;
  return <Icon className={className} />;
}
